// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users/approve": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "处理注册申请",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.AuditRegisterApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users/disable2FA": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "禁用双因素认证",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users/enable2FA": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "开启双因素认证",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.Enable2FAResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.LoginResponse"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.RegisterResponse"
                        }
                    }
                }
            }
        },
        "/users/registerApplications": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "获取注册申请列表",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ListRegisterApplicationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.ListRegisterApplicationResponse"
                        }
                    }
                }
            }
        },
        "/users/renewRecoveryCodes": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "刷新恢复码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/common.StringArrayValue"
                        }
                    }
                }
            }
        },
        "/users/validOTP": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "验证双因素密码",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/common.StringValue"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.LoginResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户"
                ],
                "summary": "更新个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "占位符",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "common.ListCondition": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "description": "排序字段",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "perPage": {
                    "description": "每页大小",
                    "type": "integer"
                }
            }
        },
        "common.StringArrayValue": {
            "type": "object",
            "properties": {
                "values": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "common.StringValue": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "user.AuditRegisterApplicationRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "description": "注册的请求 id 列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "isApproved": {
                    "description": "是否通过申请",
                    "type": "boolean"
                },
                "rejectReason": {
                    "description": "拒绝原因",
                    "type": "string"
                }
            }
        },
        "user.Enable2FAResponse": {
            "type": "object",
            "properties": {
                "recoveryCodes": {
                    "description": "恢复码",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "url": {
                    "description": "OTP 认证 url",
                    "type": "string"
                }
            }
        },
        "user.ListRegisterApplicationRequest": {
            "type": "object",
            "properties": {
                "listCondition": {
                    "description": "分页信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.ListCondition"
                        }
                    ]
                },
                "status": {
                    "description": "申请状态，approved（已通过）、rejected（已拒绝）、pending（待审核）",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "user.ListRegisterApplicationResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "详情",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.RegisterApplicationDetail"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "user.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "user.LoginResponse": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "userId",
                    "type": "string"
                },
                "name": {
                    "description": "用户名",
                    "type": "string"
                },
                "need2FA": {
                    "description": "是否需要双因素验证",
                    "type": "boolean"
                },
                "permissions": {
                    "description": "权限列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token": {
                    "description": "凭证",
                    "type": "string"
                }
            }
        },
        "user.RegisterApplicationDetail": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "申请时间",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "reason": {
                    "description": "申请原因",
                    "type": "string"
                },
                "rejectReason": {
                    "description": "拒绝原因",
                    "type": "string"
                },
                "status": {
                    "description": "状态，approved（已通过）、rejected（已拒绝）、pending（待审核）",
                    "type": "string"
                }
            }
        },
        "user.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "reason": {
                    "description": "如果注册需要审核，此字段为申请原因",
                    "type": "string"
                }
            }
        },
        "user.RegisterResponse": {
            "type": "object",
            "properties": {
                "needAudit": {
                    "description": "是否需要审核",
                    "type": "boolean"
                }
            }
        },
        "user.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.StringValue"
                        }
                    ]
                },
                "name": {
                    "description": "昵称",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.StringValue"
                        }
                    ]
                },
                "password": {
                    "description": "密码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/common.StringValue"
                        }
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "token": {
            "description": "jwt string",
            "type": "apiKey",
            "name": "X-Access-Token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "PChat API",
	Description:      "PChat 的接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
