basePath: /v1
definitions:
  admin.PasswordSetting:
    properties:
      isEnabled:
        description: 是否开启密码设置
        type: boolean
      maxLength:
        description: 最大长度
        type: integer
      minLength:
        description: 最小长度
        type: integer
      mustHasLowercase:
        description: 必须包含小写字母
        type: boolean
      mustHasNumber:
        description: 必须包含数字
        type: boolean
      mustHasSpecialCode:
        description: 必须包含特殊字符
        type: boolean
      mustHasUppercase:
        description: 必须包含大写字母
        type: boolean
    type: object
  admin.RegisterSetting:
    properties:
      mustBeApprovedBeforeRegister:
        description: 注册成功前需要审核
        type: boolean
    type: object
  admin.UpdateAIRequest:
    properties:
      isEnabled:
        description: 是否启用
        type: boolean
      key:
        description: 密钥
        type: string
      model:
        description: 模型名称
        type: string
      provider:
        allOf:
        - $ref: '#/definitions/admin.UpdateAIRequest_AIProvider'
        description: 服务提供者
      proxy:
        description: 代理 URL
        type: string
    type: object
  admin.UpdateAIRequest_AIProvider:
    enum:
    - 0
    type: integer
    x-enum-varnames:
    - UpdateAIRequest_OPEN_AI
  admin.UpdateAccountSettingRequest:
    properties:
      password:
        allOf:
        - $ref: '#/definitions/admin.PasswordSetting'
        description: 密码设置
      register:
        allOf:
        - $ref: '#/definitions/admin.RegisterSetting'
        description: 注册设置
      tokenKey:
        description: token 密钥
        type: string
      tokenValidSecond:
        description: token 有效秒数
        type: integer
    type: object
  admin.UpdateChatSettingRequest:
    properties:
      allowRollback:
        description: 允许撤回
        type: boolean
      sendEmailIfNotOnline:
        description: 使用邮箱发送离线消息
        type: boolean
      showMessageReadStatus:
        description: 展示已读信息
        type: boolean
    type: object
  admin.UpdateOSSSettingRequest:
    properties:
      accessKey:
        description: AK
        type: string
      endpoint:
        description: 服务 host
        type: string
      privateBucket:
        description: 私密 bucket
        type: string
      provider:
        allOf:
        - $ref: '#/definitions/admin.UpdateOSSSettingRequest_OSSProvider'
        description: 服务提供者
      publicBucket:
        description: 公共 bucket
        type: string
      secretAccessKey:
        description: SK
        type: string
      validSecond:
        description: 签发的 URL 有效时间
        type: integer
    type: object
  admin.UpdateOSSSettingRequest_OSSProvider:
    enum:
    - 0
    type: integer
    x-enum-varnames:
    - UpdateOSSSettingRequest_MINIO
  admin.UpdateSMTPSettingRequest:
    properties:
      host:
        description: 服务器地址
        type: string
      password:
        description: 密码
        type: string
      port:
        description: 服务端口
        type: integer
      protocol:
        allOf:
        - $ref: '#/definitions/admin.UpdateSMTPSettingRequest_Protocol'
        description: 协议
      senderName:
        description: 发送人名称
        type: string
      userName:
        description: 用户名
        type: string
    type: object
  admin.UpdateSMTPSettingRequest_Protocol:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - UpdateSMTPSettingRequest_SMTP
    - UpdateSMTPSettingRequest_SMTPS
  admin.UpdateSettingRequest:
    properties:
      account:
        allOf:
        - $ref: '#/definitions/admin.UpdateAccountSettingRequest'
        description: 账户设置
      ai:
        allOf:
        - $ref: '#/definitions/admin.UpdateAIRequest'
        description: ai 设置
      chat:
        allOf:
        - $ref: '#/definitions/admin.UpdateChatSettingRequest'
        description: chat 设置
      oss:
        allOf:
        - $ref: '#/definitions/admin.UpdateOSSSettingRequest'
        description: oss 设置
      smtp:
        allOf:
        - $ref: '#/definitions/admin.UpdateSMTPSettingRequest'
        description: 邮箱设置
    type: object
  common.BoolValue:
    properties:
      value:
        type: boolean
    type: object
  common.DetailRequest:
    properties:
      id:
        description: '@gotags: valid:"required,objectId"'
        type: string
    type: object
  common.EmptyResponse:
    type: object
  common.GetPutObjectURLRequest:
    properties:
      isPrivate:
        description: 是否私有
        type: boolean
      key:
        description: 文件名
        type: string
      validSecond:
        description: 有效时间
        type: integer
    type: object
  common.GetPutObjectURLResponse:
    properties:
      url:
        type: string
    type: object
  common.ListCondition:
    properties:
      orderBy:
        description: 排序字段
        items:
          type: string
        type: array
      page:
        description: 页码
        type: integer
      perPage:
        description: 每页大小
        type: integer
    type: object
  common.StringArrayValue:
    properties:
      values:
        items:
          type: string
        type: array
    type: object
  common.StringValue:
    properties:
      value:
        type: string
    type: object
  pchat_pb_todo.RemindSetting:
    properties:
      isRepeatable:
        description: 是否重复
        type: boolean
      remindAt:
        description: 提醒时间
        type: string
      repeatDateOffset:
        description: 重复间隔
        type: integer
      repeatType:
        description: 重复类型，day（天）、week（周）、month（月）、year（年）、holiday（节假日）、weekday（工作日）
        type: string
    type: object
  todo.ListTodoRecordsRequest:
    properties:
      hasBeenDone:
        allOf:
        - $ref: '#/definitions/common.BoolValue'
        description: 是否已完成
      listCondition:
        allOf:
        - $ref: '#/definitions/common.ListCondition'
        description: 分页
      searchKey:
        description: 关键字
        type: string
    type: object
  todo.ListTodoRecordsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/todo.TodoRecordDetail'
        type: array
      total:
        type: integer
    type: object
  todo.TodoRecordDetail:
    properties:
      content:
        description: 内容
        type: string
      createdAt:
        description: 创建时间
        type: string
      doneAt:
        description: 完成时间
        type: string
      hasBeenDone:
        description: 是否已完成
        type: boolean
      id:
        description: id
        type: string
      images:
        description: 图片
        items:
          type: string
        type: array
      remindSetting:
        allOf:
        - $ref: '#/definitions/pchat_pb_todo.RemindSetting'
        description: 提醒时间
      todoId:
        description: 关联的 todo.id
        type: string
      updatedAt:
        description: 更新时间
        type: string
      userId:
        description: 关联 user
        type: string
    type: object
  todo.UpsertTodoRequest:
    properties:
      content:
        description: 内容
        type: string
      id:
        description: id
        type: string
      images:
        description: 图片
        items:
          type: string
        type: array
      needRemind:
        description: 是否需要提醒
        type: boolean
      remindSetting:
        allOf:
        - $ref: '#/definitions/pchat_pb_todo.RemindSetting'
        description: 提醒设置
    type: object
  user.AuditRegisterApplicationRequest:
    properties:
      ids:
        description: 注册的请求 id 列表
        items:
          type: string
        type: array
      isApproved:
        description: 是否通过申请
        type: boolean
      rejectReason:
        description: 拒绝原因
        type: string
    type: object
  user.Enable2FAResponse:
    properties:
      recoveryCodes:
        description: 恢复码
        items:
          type: string
        type: array
      url:
        description: OTP 认证 url
        type: string
    type: object
  user.ListRegisterApplicationRequest:
    properties:
      listCondition:
        allOf:
        - $ref: '#/definitions/common.ListCondition'
        description: 分页信息
      status:
        description: 申请状态，approved（已通过）、rejected（已拒绝）、pending（待审核）
        items:
          type: string
        type: array
    type: object
  user.ListRegisterApplicationResponse:
    properties:
      items:
        description: 详情
        items:
          $ref: '#/definitions/user.RegisterApplicationDetail'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  user.LoginRequest:
    properties:
      email:
        description: 邮箱
        type: string
      password:
        description: 密码
        type: string
    type: object
  user.LoginResponse:
    properties:
      avatar:
        description: 头像
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: userId
        type: string
      name:
        description: 用户名
        type: string
      need2FA:
        description: 是否需要双因素验证
        type: boolean
      permissions:
        description: 权限列表
        items:
          type: string
        type: array
      token:
        description: 凭证
        type: string
    type: object
  user.RegisterApplicationDetail:
    properties:
      createdAt:
        description: 申请时间
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: id
        type: string
      reason:
        description: 申请原因
        type: string
      rejectReason:
        description: 拒绝原因
        type: string
      status:
        description: 状态，approved（已通过）、rejected（已拒绝）、pending（待审核）
        type: string
    type: object
  user.RegisterRequest:
    properties:
      email:
        description: 邮箱
        type: string
      password:
        description: 密码
        type: string
      reason:
        description: 如果注册需要审核，此字段为申请原因
        type: string
    type: object
  user.RegisterResponse:
    properties:
      needAudit:
        description: 是否需要审核
        type: boolean
    type: object
  user.UpdateProfileRequest:
    properties:
      avatar:
        allOf:
        - $ref: '#/definitions/common.StringValue'
        description: 头像
      name:
        allOf:
        - $ref: '#/definitions/common.StringValue'
        description: 昵称
      password:
        allOf:
        - $ref: '#/definitions/common.StringValue'
        description: 密码
    type: object
info:
  contact: {}
  description: PChat 的接口文档
  title: PChat API
  version: "1.0"
paths:
  /admin/setting:
    put:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/admin.UpdateSettingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.EmptyResponse'
      summary: 修改设置
      tags:
      - 设置
  /common/putObjectURL:
    get:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/common.GetPutObjectURLRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.GetPutObjectURLResponse'
      summary: 获取上传到 oss 的链接
      tags:
      - 通用
  /todos:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/todo.UpsertTodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 创建、修改待办
      tags:
      - 待办管理
  /todos/:id:
    delete:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/common.DetailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 删除待办
      tags:
      - 待办管理
  /todos/records:
    get:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/todo.ListTodoRecordsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/todo.ListTodoRecordsResponse'
      summary: 获取待办列表
      tags:
      - 待办管理
  /todos/records/:id:
    get:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/common.DetailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/todo.TodoRecordDetail'
      summary: 获取一条待办内容
      tags:
      - 待办管理
  /users/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: 占位符
        in: path
        name: id
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 更新个人信息
      tags:
      - 账户
  /users/approve:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.AuditRegisterApplicationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 处理注册申请
      tags:
      - 账户
  /users/disable2FA:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 禁用双因素认证
      tags:
      - 账户
  /users/enable2FA:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.Enable2FAResponse'
      summary: 开启双因素认证
      tags:
      - 账户
  /users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginResponse'
      summary: 登录
      tags:
      - 账户
  /users/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.RegisterResponse'
      summary: 注册
      tags:
      - 账户
  /users/registerApplications:
    get:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.ListRegisterApplicationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ListRegisterApplicationResponse'
      summary: 获取注册申请列表
      tags:
      - 账户
  /users/renewRecoveryCodes:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.StringArrayValue'
      summary: 刷新恢复码
      tags:
      - 账户
  /users/validOTP:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/common.StringValue'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginResponse'
      summary: 验证双因素密码
      tags:
      - 账户
securityDefinitions:
  token:
    description: jwt string
    in: header
    name: X-Access-Token
    type: apiKey
swagger: "2.0"
